Remove identifiers from integration tests
Financial-Times/relations-api pull request #19
Opened 2021-03-24 15:01 UTC by asparuhft

# Description

## What

Identifiers are wrongly used in the content text fixtures because the content-rw-neo4j is not supporting them.

Furthermore, identifiers are cleaned up in the integration tests although they are not created.

## Why

JIRA Ticket [UPPSF-2222](https://financialtimes.atlassian.net/browse/UPPSF-2222)

## Scope and particulars of this PR (Please tick all that apply)

- [X] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-03-25 14:50 UTC, mchompalova requested changes

2021-03-25 14:50 UTC, mchompalova commented on relations/fixtures/Content-3fc9fe3e-af8c-1a1a-961a-e5065392bb31.json
> -  "byline": "By Matthew Garrahan in Los Angeles",
Why do we remove byline here?

2021-03-25 14:57 UTC, asparuhft commented on relations/fixtures/Content-3fc9fe3e-af8c-1a1a-961a-e5065392bb31.json
> -  "byline": "By Matthew Garrahan in Los Angeles",
Just discussed this topic with Kalin. I will revert the changes on the content fixtures in all of the PRs I have raised.

2021-03-25 16:04 UTC, mchompalova reviewed
I'm a bit confused. The description says: Identifiers are wrongly used in the content text fixtures because the content-rw-neo4j is not supporting them.
And still we leave them in the fixtures?

2021-03-26 07:52 UTC, asparuhft commented
The content-rw-neo4j is ignoring parameters like identifiers, byline, brands. Furthermore, these identifiers are semantically different from the ones created by concepts-rw-neo4j service. I just decided to clean up these parameters (identifiers, byline, ...) from the content fixtures as they are not used. However, Kalin proposed that we keep them as these are more close to the ones that the content-rw-neo4j gets from Kafka through the ingester. These makes sense so I reverted the changes on the content fixtures. 
What is important in this PR is that we are trying to delete Identifiers in the cleanup part of the integration tests, which is actually not needed because no Identifiers are created.

2021-03-26 07:55 UTC, mchompalova commented
> The content-rw-neo4j is ignoring parameters like identifiers, byline, brands. Furthermore, these identifiers are semantically different from the ones created by concepts-rw-neo4j service. I just decided to clean up these parameters (identifiers, byline, ...) from the content fixtures as they are not used. However, Kalin proposed that we keep them as these are more close to the ones that the content-rw-neo4j gets from Kafka through the ingester. These makes sense so I reverted the changes on the content fixtures.
> What is important in this PR is that we are trying to delete Identifiers in the cleanup part of the integration tests, which is actually not needed because no Identifiers are created.

Thank you for the detailed explanation. Can you squash the two commits into one?

2021-03-26 08:16 UTC, karsov approved these changes

2021-03-26 12:30 UTC, mchompalova approved these changes

2021-03-29 14:23 UTC, karsov approved these changes

2021-03-29 14:58 UTC, merged