Fix/uppsf 2793 migrate to cmneo4j driver
Financial-Times/relations-api pull request #22
Opened 2021-11-03 14:25 UTC by ivanruski

# Description

Migrating to from `neo-utils-go` to `cm-neo4j-driver` as well as upgrading `go-logger` and `http-handlers`.

Also the cypher queries are changed a bit because of the way cm-neo4j-driver works. 

## Why

[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-2793)

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-11-09 12:53 UTC, mchompalova requested changes
LGTM. A few minor comments

2021-11-09 12:53 UTC, mchompalova commented on README.md
>  Execute test:
**suggestion**: We can add a section how to run integration tests as well.

2021-11-09 12:53 UTC, mchompalova commented on app.go
> +func router(hh relations.HttpHandlers, apiYml string, log *logger.UPPLogger) http.Handler {
Why do we remove the pointer for apiYml?

2021-11-09 12:53 UTC, mchompalova commented on go.mod
>  	github.com/jmcvetta/neoism v1.3.1
Go mod tidy will remove neoism.

2021-11-10 11:41 UTC, ManoelMilchev commented on app.go
> +func router(hh relations.HttpHandlers, apiYml string, log *logger.UPPLogger) http.Handler {
Hello, I believe that we are removing the pointer because we are dereferencing earlier when calling the `runServer` function. Take a look -> [HERE](https://github.com/Financial-Times/relations-api/pull/22/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR71-R73)

2021-11-10 12:10 UTC, mchompalova commented on app.go
> +func router(hh relations.HttpHandlers, apiYml string, log *logger.UPPLogger) http.Handler {
Yes, I think it's easier to pass a reference rather than a copy of the whole object.

2021-11-15 09:47 UTC, ivanruski commented on README.md
>  Execute test:
Done

2021-11-15 09:57 UTC, ivanruski commented on go.mod
>  	github.com/jmcvetta/neoism v1.3.1
done

2021-11-15 09:57 UTC, ivanruski commented on README.md
> +--cache-duration        Duration Get requests should be cached for. e.g. 2h45m would set the max-age value to '7440' seconds (env $CACHE_DURATION) (default "30s")
done

2021-11-15 10:08 UTC, ivanruski commented on app.go
> +func router(hh relations.HttpHandlers, apiYml string, log *logger.UPPLogger) http.Handler {
I changed `apiYml` from `*string` to `string` because I wanted to take advantage of the go feature which lets you specify the type only once (line 77):
```
func runServer(neoURL, port, cacheDuration, apiYml string, log, dbDriverLog *logger.UPPLogger) {
```

I did this because `runServer` has 6 parameters and it's signature will be really long and hard to read if we specify the type of each param separately.


In this case passing a string by value instead of a pointer to a string is not a problem and also we are not coping the entire string because in go the string type is holding a reference to the actual string and it's never copied.

https://github.com/golang/go/blob/6f327f7b889b81549d551ce6963067267578bd70/src/runtime/string.go#L238

2021-11-15 16:28 UTC, mchompalova approved these changes
LGTM

2021-11-16 07:26 UTC, ManoelMilchev approved these changes
LGTM

2021-11-25 11:06 UTC, merged